### PR TITLE
Remove rsBottomPanel and contents

### PR DESCRIPTION
**Pull request by cghende1**
…along with all of the corresponding gui objects and actions

### CODE REVIEW

**Comment by jgerszty** [comment]
Looks good, +1

**Comment by cmbartee** [comment]
One small issue: I don't think there's any reason for the commented-out line on line 416 to exist; probably best to delete it.

Also, I'm not sure if we can do anything about it at this point, but this branch has the wrong name - it should be **us-48** since it is addressing user story #48.

**Comment by cghende1** [comment]
This is task 58 which is a part of user story 48. We never resolved how to handle that.

I propose that this PR merge into us-48 rather than master.

**Comment by cghende1** [comment]
Closing this PR and opening a new one targeted to us-48.

**Pull request closed without merging**
