### PR TITLE
Us 13

### PR DESCRIPTION
**Pull request by cghende1**

### CODE REVIEW

**Comment by christopher-henderson** [comment]
The timer appears to be working, but the interface is both confusing and getting horribly mangled on my instance.

The task toolbar sticks to whatever toolbar it was last. It fails to swap to the task toolbar until moused over. Not sure if this was behavior from before.

The update timer button does not work. I have to close the task tree and reopen it. And the only way that I can figure to do even that is leave the task menu and come back.

NPE at net.sf.memoranda.TaskImpl.getPrintableTime(Unknown Source) when stopping the timer.

**Comment by cghende1** [comment]
_sigh_, I posted under my personal account. Reposting in order to get the stats under this account.

The timer appears to be working, but the interface is both confusing and getting horribly mangled on my instance.

The task toolbar sticks to whatever toolbar it was last. It fails to swap to the task toolbar until moused over. Not sure if this was behavior from before.

The update timer button does not work. I have to close the task tree and reopen it. And the only way that I can figure to do even that is leave the task menu and come back.

NPE at net.sf.memoranda.TaskImpl.getPrintableTime(Unknown Source) when stopping the timer.

**Comment by crdiaz3** [comment]
I figured it out. I added an attribute to the Task object, and memoranda is loading old tasks that get stored locally. Since those old tasks do not have the elapsedTime attribute, everything breaks.

The quick-fix is to checkout any working branch (master), run memoranda and delete old tasks. Switch back to US-13 and it should run as expected (make sure the java process is killed before testing new branch).

Should I apply a fix to recreate old tasks, or should we ignore this since we have not officially "released" the product yet?

**Comment by christopher-henderson** [comment]
No. In the context of the class project the product IS released. We are working on a newer version. We must work on the assumption that task exists. We have to perform the proper migration.

**Comment by crdiaz3** [comment]
Fix has been applied to migrate old tasks.

**Comment by cghende1** [comment]
There are merge conflicts.

**Comment by crdiaz3** [comment]
Fixed all merge conflicts

**Comment by cghende1** [comment]
I cannot start the application.

java.io.FileNotFoundException: /Users/chris/.memoranda/127593a8-dfdb-2275-26dc/.tasklist (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at java.io.FileInputStream.<init>(FileInputStream.java:93)
    at net.sf.memoranda.util.FileStorage.openDocument(Unknown Source)
    at net.sf.memoranda.util.TaskListVersioning.upgrade1_1d1(Unknown Source)
    at net.sf.memoranda.util.TaskListVersioning.upgradeTaskList(Unknown Source)
    at net.sf.memoranda.util.FileStorage.openTaskList(Unknown Source)
    at net.sf.memoranda.CurrentProject.<clinit>(Unknown Source)
    at net.sf.memoranda.ui.ProjectsPanel.jbInit(Unknown Source)
    at net.sf.memoranda.ui.ProjectsPanel.<init>(Unknown Source)
    at net.sf.memoranda.ui.AppFrame.<init>(Unknown Source)
    at net.sf.memoranda.ui.App.<init>(Unknown Source)
    at net.sf.memoranda.Start.main(Unknown Source)

**Comment by crdiaz3** [comment]
Is that a valid path?

**Comment by cghende1** [comment]
It is completely valid. /Users/chris/.memoranda/127593a8-dfdb-2275-26dc/ exists, but .tasklist does not.

**Comment by crdiaz3** [comment]
Aha, a new project was added, but no tasks were created for it. I'll have to add a check for that

**Comment by cghende1** [comment]
I'm uncomfortable merging this branch given that we are fumbling around with edge cases one at a time. We do not want to attempt to recover from yet another edge case come Friday.

We would definitely needs unit tests to prove this change if want it in master. As such, we may not have it for Friday.

**Comment by crdiaz3** [comment]
I went ahead and applied the fix anyway.

**Comment by cghende1** [comment]
Thank you very much.

**Comment by ajcallos** [comment]
+1. Pre-existing tasks with children run the timer with no problem.

**Comment by cghende1** [comment]
Tested it on Mac. Looks green.

**Comment by jgerszty** [comment]
Stay gold, Ponyboy.

**Pull request merged**
