### PR TITLE
User Story #22

### PR DESCRIPTION
**Pull request by cghende1**

### CODE REVIEW

**Comment by crdiaz3** [comment]
Success. Friendly error is now displayed when the URL path provided is not absolute.

**Comment by jgerszty** [comment]
+1 works here

**Comment by cmbartee** [comment]
Seems to work well - a few small notes:
Typo in error message string on line 226 - "interet"
Current commit reverts the changes on the .gitignore file; be sure not to merge that into master

Aside from that, no problems, +1 from me once the typo is fixed.

**Comment by cghende1** [comment]
Done.

**Pull request merged**
