### PR TITLE
Add check to move cursor

### PR DESCRIPTION
**Pull request by cghende1**

### CODE REVIEW

**Comment by cghende1** [comment]
Needs a rebase for the tests.

**Comment by jgerszty** [comment]
It may have applied it twice(?), but says checks passed.

**Comment by cghende1** [comment]
Nice, I think Travis building and testing each node in the commit. https://github.com/cst316/spring16project-Dart/commit/dbfd030a7ca1bc89a45ddf11a8a4939d33759bf7 failed. Everything is fine.

**Comment by christopher-henderson** [comment]
This works fine when the preference is to close the app completely. However, given the "hide" preference I can't seem to ever get the frame back.

**Comment by jgerszty** [comment]
This doesn't have to do with the app frame, this is just for the HTML editor.

**Comment by cghende1** [comment]
Looks good to me! Artisanal.

**Comment by cmbartee** [comment]
Works well - changing styles from drop down menus now has changes immediately reflected in editor.

**Comment by ajcallos** [comment]
Tiny line does great things

**Pull request merged**
